[versions]
#   https://plugins.gradle.org/plugin/org.jetbrains.kotlin.multiplatform
jetbrains-kotlinMultiplatform = "2.0.0-RC1"

[libraries]

[plugins]
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlinMultiplatform" }